# these hooks are run before(pre) commit
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # same as ruff version
    # can keep this updated with `uv run pre-commit autoupdate`
    rev: v0.14.3
    hooks:
      # formatter
      - id: ruff-format
      # linter
      - id: ruff-check
        args: [--fix]
