name: CI for greet-user # Friendly name

on:
  push:
    paths:
      - "greet-user/**"
  pull_request:
    paths:
      - "greet-user/**"

defaults:
  run:
    working-directory: greet-user

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Format with ruff
        run: uv run ruff format --check .

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Test with pytest
        run: uv run pytest --cov=src/greet_user

      - name: Build docs
        run: uv run mkdocs build
